version: '3.8'

services:
  ms-sum:
    build: ./ms-sum
    ports:
      - '8080:8080'

  ms-subtract:
    build: ./ms-subtract
    ports:
      - '8081:8080'
    environment:
      - SUM_SERVICE_URL=http://ms-sum:8080